import { useState } from "react";
import { sdgList } from "../components/ProjectForm/SdgOptions"; 

export default function useProjectFormState(props) {
  const {
    projectID: existingProjectID,
    standar: existingStandar,
    vintage: existingVintage,
    volumen: existingVolumen,
    name: existingName,
    projectLink: existingProjectLink,
    tech: existingTech,
    corsia: existingCorsia,
    sdg: existingSdg,
    pais: existingPais,
    continente: existingContinente,
    disponible: existingDisponible,
    stock: existingStock,
    precioVenta: existingPrecioVenta,
    precioCorp: existingPrecioCorp,
    floorPrice: existingFloorPrice,
    purchasePrice: existingPurchasePrice,
    thirdPartPrice: existingThirdPartPrice,
    contrato: existingContrato,
    mktDate: existingMktDate,
    proveedor: existingProveedor,
    sede: existingSede,
    misha: existingMisha,
    mailingList: existingMailingList,
    brokerList: existingBrokerList,
    equipo: existingEquipo,
    tdService: existingTdService,
    typeOfContract: existingTypeOfContract,
    actualDataVolume: existingActualDataVolume,
    netVolume: existingNetVolume,
    sectorTD: existingSectorTD,
    status: existingStatus,
    stage: existingStage,
    rpStartDate: existingRpStartDate,
    rpEndDate: existingRpEndDate,
    firstCPDate: existingFirstCPDate,
    notas: existingNotas,
    notasExtra: existingNotasExtra,
    ccb: existingCcb,
    ccp: existingCcp,
    projectType: existingProjectType,
    icroa: existingIcroa,
    methodology: existingMethodology,
    registrationDate: existingRegistrationDate,
    buyerCountry: existingBuyerCountry,
    doubleCountingRisk: exisitngDoubleCountingRisk,
    prePayment: existingPrePayment,
    regulatedMarket: existingRegulatedMarket,
    sdgSelected: existingSdgSelected,
    sdgImages: existingSdgImages,
    tdInfo: existingTdInfo,
    files: existingFiles,
  } = props;

  return {
    // General
    projectID: useState(existingProjectID || ""),
    standar: useState(existingStandar || ""),
    vintage: useState(existingVintage || ""),
    volumen: useState(existingVolumen || ""),
    name: useState(existingName || ""),
    projectLink: useState(existingProjectLink || ""),
    tech: useState(existingTech || ""),
    corsia: useState(existingCorsia || ""),
    sdg: useState(existingSdg || ""),
    pais: useState(existingPais || ""),
    continente: useState(existingContinente || ""),
    disponible: useState(existingDisponible || ""),
    stock: useState(existingStock || ""),

    // Precios
    precioVenta: useState(existingPrecioVenta || ""),
    precioCorp: useState(existingPrecioCorp || ""),
    floorPrice: useState(existingFloorPrice || ""),
    purchasePrice: useState(existingPurchasePrice || ""),
    thirdPartPrice: useState(existingThirdPartPrice || ""),

    // Contrato
    contrato: useState(existingContrato || ""),
    mktDate: useState(existingMktDate || ""),

    // Proveedor
    proveedor: useState(existingProveedor || ""),
    sede: useState(existingSede || ""),
    misha: useState(existingMisha || ""),
    mailingList: useState(existingMailingList || ""),
    brokerList: useState(existingBrokerList || ""),
    equipo: useState(existingEquipo || ""),
    prePayment: useState(existingPrePayment || ""),

    // TD
    tdService: useState(existingTdService || ""),
    typeOfContract: useState(existingTypeOfContract || ""),
    actualDataVolume: useState(existingActualDataVolume || ""),
    netVolume: useState(existingNetVolume || ""),
    sectorTD: useState(existingSectorTD || ""),
    status: useState(existingStatus || ""),
    stage: useState(existingStage || ""),
    rpStartDate: useState(existingRpStartDate || ""),
    rpEndDate: useState(existingRpEndDate || ""),

    // Extras
    firstCPDate: useState(existingFirstCPDate || ""),
    notas: useState(existingNotas || ""),
    notasExtra: useState(existingNotasExtra || ""),
    ccb: useState(existingCcb || ""),
    ccp: useState(existingCcp || ""),
    projectType: useState(existingProjectType || ""),
    icroa: useState(existingIcroa || ""),
    methodology: useState(existingMethodology || ""),
    registrationDate: useState(existingRegistrationDate || ""),
    buyerCountry: useState(existingBuyerCountry || []),
    doubleCountingRisk: useState(exisitngDoubleCountingRisk || ""),
    regulatedMarket: useState(existingRegulatedMarket || ""),
    tdInfo: useState(existingTdInfo || ""),
    files: useState(existingFiles || []),

    // SDG
    sdgSelected: useState(existingSdgSelected || []),
    sdgImages: useState(existingSdgImages || []),
    checkedState: useState(new Array(sdgList.length).fill(false)),
  };
}
